project:
  type: website

website:
  title: "Gjandebeur Projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: scripts.qmd
        text: Scripts

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



